function y = lpfilter30hz(x)
%LPFILTER30HZ Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.0 and the DSP System Toolbox 9.2.
% Generated on: 25-Nov-2016 21:47:13

%#codegen

% To generate C/C++ code from this function use the codegen command. Type
% 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    % % Equiripple Lowpass filter designed using the FIRPM function.
    %
    % % All frequency values are in Hz.
    % Fs = 100;  % Sampling Frequency
    %
    % Fpass = 30;              % Passband Frequency
    % Fstop = 50;              % Stopband Frequency
    % Dpass = 0.057501127785;  % Passband Ripple
    % Dstop = 0.0001;          % Stopband Attenuation
    % dens  = 20;              % Density Factor
    %
    % % Calculate the order from the parameters using FIRPMORD.
    % [N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);
    %
    % % Calculate the coefficients using the FIRPM function.
    % b  = firpm(N, Fo, Ao, W, {dens});
    
    Hd = dsp.FIRFilter( ...
        'Numerator', [-0.00145168459677622 0.00788049850315635 ...
        -0.0262852466833652 0.0693695997831708 -0.171459968635195 ...
        0.621888592929825 0.621888592929825 -0.171459968635195 ...
        0.0693695997831708 -0.0262852466833652 0.00788049850315635 ...
        -0.00145168459677622]);
end

y = step(Hd,x);


% [EOF]
